name: Auto Blog LeetCode Solutions

on:
  push:
    branches: [master]
    paths:
      - "**.py"
      # - "!.github/scripts/create_blog_post.py"

jobs:
  create-blog-post:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout LeetCode repo
        uses: actions/checkout@v3
        with:
          path: leetcode-repo
          fetch-depth: 2 # Fetch the last two commits for diff comparison

      - name: Checkout blog repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/v2.gahmed
          token: ${{ secrets.BLOG_REPO_TOKEN }}
          path: blog-repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Create blog post
        run: |
          cd leetcode-repo
          python .github/scripts/create_blog_post.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for changes
        id: check_changes
        run: |
          cd blog-repo
          if [[ -n $(git status -s) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push blog post
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          cd blog-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add src/content/blog/
          git commit -m "Add new LeetCode solution blog post [skip ci]"
          git push
